# Generated by Django 5.2.6 on 2025-10-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_category', models.CharField(choices=[('Concerts', 'Concerts'), ('Sports', 'Sports'), ('Seminars', 'Seminars'), ('Others', 'Others')], max_length=50)),
                ('event_venue', models.CharField(max_length=150)),
                ('event_date', models.DateField()),
                ('event_time_in', models.TimeField()),
                ('event_time_out', models.TimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
