# Generated by Django 5.2.6 on 2025-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
