# Generated by Django 5.2.6 on 2025-11-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.event'),
            preserve_default=False,
        ),
    ]
