# Generated by Django 5.2.7 on 2025-11-11 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_ticket_event_name_ticket_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'event'], name='accounts_ti_user_id_e38597_idx'),
        ),
    ]
