# Generated by Django 5.2.6 on 2025-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
